trigger: none # Non-PR branches
pr:
  branches:
    include:
    - '*'

jobs:
- job: ADAL_Windows_AutomatedCommit_Azure
  displayName: ADAL Windows Automated Commit Azure
  pool:
    vmImage: windows-2019
  timeoutInMinutes: 30
  cancelTimeoutInMinutes: 1
  workspace:
    clean: all

  steps:
  - checkout: self
    clean: true
    submodules: true

  - task: UsePythonVersion@0
    displayName: Use Python 3.x

  - task: Bash@3
    displayName: 'Pre-commit'
    inputs:
      targetType: filePath
      filePath: './pre-commit'
    env:
      GIT_AUTHOR_NAME: Vincent Verdant
      GIT_COMMITTER_NAME: Vincent Verdant
      GIT_AUTHOR_EMAIL: vinverd@microsoft.com
      GIT_COMMITTER_EMAIL: vinverd@microsoft.com
